### ISSUE TITLE
Initial set of features

### ISSUE THREAD

**Issue by amnk** [blancmanges/gatekeeper#5]
- [x] `-1, 0, +1` would be ok for voting (even hardcoded, till we figure out how to configure them per repo);
- [ ] Support of automated merge if all requested people approved the PR (for no we might disable actual merge and just oupput something to console);
- [x] On each run, create a state of all open PRs in the repo; `state` means list of people to review, last modification date, last review date, action from author needed;

**Comment by kgadek** [comment]
1st & 3rd are probably done. 2nd is split into #18
